### ISSUE TITLE
Revisión General del Proyecto

### ISSUE THREAD

**Issue by mikenieva** [AMHymyilee/cdmx-2018-06-bc-core-am-cipher#1]
Adriana,

- Bien por tu proyecto a nivel diseño y estrategia UX. Me pareció bastante dedicada y detallada.

- En general, el proyecto está muy bien. Recuerda que es muy importante que tu código HTML lo pases por esta URL: http://htmlhint.com/ ... ya que tienes muchos errores de etiquetas y es necesario corregirlos. 

![screen shot 2018-06-22 at 8 56 31 am](https://user-images.githubusercontent.com/1256678/41780394-36a5683e-75fa-11e8-881b-6495318a7ce0.png)

- También en esta URL: https://validator.w3.org/ . En ambas. Para pulir tu código al máximo.

![screen shot 2018-06-22 at 9 01 11 am](https://user-images.githubusercontent.com/1256678/41780617-d9ddb740-75fa-11e8-9c9f-6aa578fdcc03.png)

- Con respecto a tests, bien por intentar el Hacker Edition, estuviste muy cerca de resolverlo. En general pasaste todos los demás tests sin problema.

- Con tu código, me gusta que esté bien indentado y comentado. Sólo como detalle, en el `index.js` pasa tus funciones a ES6 y listo. 

Buen proyecto Adriana, me gustó tu implementación. 

Atento de tus comentarios y dudas.

**Comment by AdrianaMoraGr** [comment]
Muchas gracias por los comentarios, los voy a aplicar para mejorar este y los demás proyectos que siguen.  Agradezco su ayuda como coach.
